version: "3"

services:
 
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./student_management/student_management/.env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.http.config:/etc/nginx/nginx.conf
      #- ./assets/nginx/certs:/etc/nginx/certs
      - static_volume:/app/static
    ports:
      # - "443:443"
      - "80:80"
    restart:
      on-failure:5

volumes:
  dj_postgres_data:
  static_volume:
